blank_issues_enabled: false
contact_links:
    - name: Questions
      url: https://github.com/andrey-helldar/package-wizard/discussions
      about: Discuss any issues related to the application or templates working with it.
